name: crypto_wallet
description: Flutter App with Firebase Authentication and Firestore Tutorial - Crypto Wallet.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # Firebase Dependencies
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter.ttf
